notifications:
  email:
    recipients:
      - chris+travis@chrisdown.name
    on_success: never
    on_failure: always

language: ruby
bundler_args: --without development integration
rvm:
  - 1.9.3
  - 2.0.0
before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
script:
  - bundle exec foodcritic -f any .
  - bundle exec rubocop
