name 'rtorrent'
maintainer 'Chris Down'
maintainer_email 'chris@chrisdown.name'
license 'ISC'
description 'Installs rtorrent to run inside tmux'
long_description 'Installs rtorrent to run inside tmux'
version '1.0.1'
issues_url 'https://github.com/cdown/rtorrent-cookbook/issues'
source_url 'https://github.com/cdown/rtorrent-cookbook'
